### ISSUE TITLE
Don't scroll while ai is answering.

### ISSUE THREAD

**Issue by felixniemeyer** [pjq/ChitChat#18]
I'm using this app on Android and I downloaded it from the app store. 
I like, that it's so slim and simple.
Thank you. It's a great way to access gpt on my mobile phone. 

There is one thing that I'd like to see improved. After sending my message, GPT "starts typing". This causes the chat to scroll and makes it almost impossible to start reading while gpt is still typing. So I have to wait until gpt has finished and only then can I start reading. The scrolling can't be overriden my manual scrolling. It's like the scrolling is glued to gpts cursor while it's response keeps arriving. 

I'd like to be able to read right when GPT starts typing. A solution might be to suppress automatic scrolling while ChatGPT is typing. Or at least allow manual scrolling.

**Comment by pjq** [comment]
@felixniemeyer Thanks for your feedback.
Yes, it's one good suggestion, I am aware of this issue, it should disable the auto-scroll if user interrupt scrolling.

**Comment by pjq** [comment]
Fixed 
- https://github.com/pjq/ChitChat/pull/20

**Comment by pjq** [comment]
The new version can be downloaded from here
- https://chitchat.pjq.me/download/
